%YAML:1.0


cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [-1.0, 0.0, 0.0, 0.06]
    - [0.0, -1.0, 0.0, 0]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.59,  0.13,  -0.47,  0.19]
  distortion_model: radtan
  intrinsics: [243.649,  243.39, 320.039, 186.315] #fu, fv, cu, cv
  resolution: [640, 400]
  rostopic: /camera/infra1/image_rect_raw
cam1:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [-1.0, 0.0, 0.0, -0.062]
    - [0.0, -1.0, 0.0, 0]
    - [0.0, 0.0, 1.0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.546,  0.239,  -0.589,  0.245]
  distortion_model: radtan
  intrinsics: [242.352,  242.154, 303.934,   188.229] #fu, fv, cu, cv
  resolution: [640, 400]
  rostopic: /camera/infra2/image_rect_raw