%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [1.0, 0.0,  0.0,  0.03935]
    - [0.0, 0.0, -1.0, -0.25215]
    - [0.0, 1.0,  0.0, -0.207]
    - [0.0, 0.0,  0.0,  1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.3925, 0.1875, -0.1579, 0.08515]
  distortion_model: radtan
  # intrinsics: [458.654, 457.296, 640, 360] #fu, fv, cu, cv
  intrinsics: [443.50, 443.57, 628.22, 289.79] #fu, fv, cu, cv
  resolution: [1280, 720]
  rostopic: /cam0/image_raw
